/********************************************************************************
 *  Generated by XML Mapper, 9.1.0200.20031205.WebUpdate-RC4.03
 ********************************************************************************/

/*
 *  ENVIRONMENT
 */
filename  CashFlow 'Z:\XBRL\Cash_Flow_xbrl.xml';
filename  SXLEMAP 'Z:\XBRL\xbrl.map';
libname   CashFlow xml xmlmap=SXLEMAP access=READONLY;

/*
 *  SAMPLE USAGE
 */

title 'Table Header';
proc print data=CashFlow.Header(obs=10); run;

title 'Table Items';
proc print data=CashFlow.Items(obs=10); run;

